---
roles:
  - src: git@github.com:ccdc-opensource/ansible-role-vagrant-base-box
    scm: git
    name: ccdc.vagrant-base-box
    version: add-linux
  - src: git@github.com:ccdc-opensource/ansible-role-install-vm-tools
    scm: git
    name: ccdc.install-vm-tools
    version: install-vm-tools-linux
  - src: git@github.com:ccdc-opensource/ansible-role-compact-vm-image
    scm: git
    name: ccdc.compact-vm-image

collections:
  - devsec.hardening